
# ARENA_WIDTH = 720
# ARENA_HEIGHT = 480
ARENA_WIDTH = 300
ARENA_HEIGHT = 300
FRAME = 5

MOTIONS = ['N', 'E' ,'S', 'W', 'NE', 'SE', 'SW', 'NW']

MAX_ORGS = 20
GEN_LIMIT = 0.5 * MAX_ORGS

MAX_FOOD = 1.5 * MAX_ORGS
MAX_FOOD_SIZE = 25

AGE_UP = 20